import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
const path=resolve(process.argv[2]);
const {default:create}=await import(pathToFileURL(path).href);
const module=await create({wasmBinary:await readFile(path.replace(/\.js$/,'.wasm'))});
let state=JSON.parse(module.ccall('gui_web_create','string',['string'],['compiled-session']));
let sequence=0;
const widget=id=>state.snapshot.widgets.find(value=>value.key.id===id);
const send=operation=>{
  state=JSON.parse(module.ccall('gui_web_receive','string',['string'],[JSON.stringify({epoch:state.epoch,seq:String(++sequence),operation})]));
  assert.equal(state.error,''); assert.equal(state.ack,String(sequence));return state;
};
const editor=widget('entries.editor').key, add=widget('entries.add').key;
send({type:'edit',key:editor,base:'',value:'Rejected é'});send({type:'activate',key:add});
assert.equal(widget('entries.list').records.length,0);
assert.equal(widget('entries.status').text,'text must contain printable ASCII only');
send({type:'edit',key:editor,base:widget('entries.editor').text,value:'Compiled entry'});send({type:'activate',key:add});
assert.equal(widget('entries.list').records[0].text,'Compiled entry');
send({type:'choose',key:widget('entries.options').key,id:'heading'});assert.ok(state.service);
send({type:'service',id:state.service.id,status:'success',value:'Module heading',error:''});
assert.equal(widget('entries.heading').text,'Module heading');
send({type:'resize',width:800,height:640,scale:1.25});
assert.equal(widget('entries.editor').bounds[2],752);
send({type:'activate',key:widget('entries.task.start').key});
assert.equal(widget('entries.task.cancel').enabled,true);
send({type:'activate',key:widget('entries.task.cancel').key});
assert.equal(widget('entries.task.status').text,'Task cancelled');
send({type:'activate',key:widget('entries.task.start').key});send({type:'poll'});
assert.equal(widget('entries.task.status').text,'Counted 13 non-space bytes');
const epoch=state.epoch;send({type:'close'});assert.equal(state.snapshot.closed,true);
state=JSON.parse(module.ccall('gui_web_create','string',['string'],['recreated-session']));
assert.equal(widget('entries.list').records.length,0);
const stale=JSON.parse(module.ccall('gui_web_receive','string',['string'],[JSON.stringify({epoch,seq:'1',operation:{type:'activate',key:add}})]));
assert.equal(stale.ack,'0');assert.ok(stale.error);
module.ccall('gui_web_destroy',null,[],[]);
console.log('Compiled Wasm core validation, edits, services, geometry, close and recreation passed');
