# Prepared SDKs are explicit inputs. This file never bootstraps dependencies.
if(NOT FOUNDATION_SDK_ROOT)
  message(FATAL_ERROR "Set FOUNDATION_SDK_ROOT to a prepared SDK")
endif()
file(REAL_PATH "${FOUNDATION_SDK_ROOT}" FOUNDATION_SDK_ROOT)
get_property(_nested GLOBAL PROPERTY IN_TRY_COMPILE)
if(NOT _nested)
  find_program(_sdk_python NAMES python3 python REQUIRED NO_CMAKE_FIND_ROOT_PATH)
  execute_process(COMMAND "${_sdk_python}" "${CMAKE_CURRENT_LIST_DIR}/../../tools/sdk_verify.py"
    "${FOUNDATION_SDK_ROOT}" RESULT_VARIABLE _valid)
  if(NOT _valid EQUAL 0)
    message(FATAL_ERROR "SDK validation failed")
  endif()
endif()
file(READ "${FOUNDATION_SDK_ROOT}/sdk.json" _sdk)
string(JSON _schema GET "${_sdk}" schema_version)
if(NOT _schema EQUAL 1)
  message(FATAL_ERROR "Unsupported SDK manifest schema")
endif()
foreach(_key system processor sysroot cxx_compiler)
  string(JSON _${_key} GET "${_sdk}" target ${_key})
endforeach()
if(NOT _system STREQUAL "Linux")
  message(FATAL_ERROR "The example sysroot toolchain supports Linux targets")
endif()
foreach(_key sysroot cxx_compiler)
  if(IS_ABSOLUTE "${_${_key}}" OR "${_${_key}}" MATCHES "(^|/)\\.\\.(/|$)")
    message(FATAL_ERROR "SDK paths must remain relative to the SDK")
  endif()
  file(REAL_PATH "${FOUNDATION_SDK_ROOT}/${_${_key}}" _resolved)
  cmake_path(IS_PREFIX FOUNDATION_SDK_ROOT "${_resolved}" NORMALIZE _inside)
  if(NOT _inside OR NOT EXISTS "${_resolved}")
    message(FATAL_ERROR "Missing or escaped SDK path")
  endif()
  set(_${_key} "${_resolved}")
endforeach()
set(CMAKE_SYSTEM_NAME "${_system}")
set(CMAKE_SYSTEM_PROCESSOR "${_processor}")
set(CMAKE_CXX_COMPILER "${_cxx_compiler}")
set(CMAKE_SYSROOT "${_sysroot}")
set(CMAKE_FIND_ROOT_PATH "${CMAKE_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_FIND_USE_PACKAGE_REGISTRY OFF)
set(CMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY OFF)
list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES FOUNDATION_SDK_ROOT)

set(ENV{PKG_CONFIG_SYSROOT_DIR} "${CMAKE_SYSROOT}")
set(ENV{PKG_CONFIG_PATH} "")
string(JSON _triple GET "${_sdk}" target triple)
set(ENV{PKG_CONFIG_LIBDIR} "${CMAKE_SYSROOT}/usr/lib/${_triple}/pkgconfig:${CMAKE_SYSROOT}/usr/lib/pkgconfig:${CMAKE_SYSROOT}/usr/share/pkgconfig")
