# Prepared SDKs are explicit inputs. This file never bootstraps dependencies.
set(ENV{PYTHONDONTWRITEBYTECODE} "1")
if(NOT FOUNDATION_SDK_ROOT)
  message(FATAL_ERROR "Set FOUNDATION_SDK_ROOT to a prepared SDK")
endif()
file(REAL_PATH "${FOUNDATION_SDK_ROOT}" FOUNDATION_SDK_ROOT)
get_property(_nested GLOBAL PROPERTY IN_TRY_COMPILE)
if(NOT _nested)
  find_program(_sdk_python NAMES python3 python REQUIRED NO_CMAKE_FIND_ROOT_PATH)
  execute_process(COMMAND "${_sdk_python}" "${CMAKE_CURRENT_LIST_DIR}/../../tools/sdk_verify.py"
    "${FOUNDATION_SDK_ROOT}" RESULT_VARIABLE _valid)
  if(NOT _valid EQUAL 0)
    message(FATAL_ERROR "SDK validation failed")
  endif()
endif()
file(READ "${FOUNDATION_SDK_ROOT}/sdk.json" _sdk)
string(JSON _schema GET "${_sdk}" schema_version)
if(NOT _schema EQUAL 1)
  message(FATAL_ERROR "Unsupported SDK manifest schema")
endif()
foreach(_key system processor sysroot cxx_compiler)
  string(JSON _${_key} GET "${_sdk}" target ${_key})
endforeach()
if(_system STREQUAL "Emscripten")
  string(JSON _toolchain GET "${_sdk}" target toolchain)
  file(REAL_PATH "${FOUNDATION_SDK_ROOT}/${_toolchain}" _wasm_toolchain)
  cmake_path(IS_PREFIX FOUNDATION_SDK_ROOT "${_wasm_toolchain}" NORMALIZE _inside)
  if(NOT _inside OR NOT EXISTS "${_wasm_toolchain}")
    message(FATAL_ERROR "Missing or escaping browser SDK toolchain")
  endif()
  set(ENV{EM_CONFIG} "${FOUNDATION_SDK_ROOT}/.emscripten")
  set(ENV{EM_CACHE} "${FOUNDATION_SDK_ROOT}/cache")
  set(ENV{EM_FROZEN_CACHE} "1")
  set(FOUNDATION_NODE_EXECUTABLE "${FOUNDATION_SDK_ROOT}/node/bin/node" CACHE FILEPATH "Retained target runtime" FORCE)
  # Keep configuration probes on the same warmed cache variant as applications.
  # Assertions remain enabled in Release as part of this prepared SDK contract.
  set(CMAKE_CXX_FLAGS_INIT "-fexceptions")
  set(CMAKE_EXE_LINKER_FLAGS_INIT "-sASSERTIONS=1")
  include("${_wasm_toolchain}")
  # Supplier CMake sets direct launcher paths; route every later Ninja command
  # through the retained wrappers so frozen-cache settings survive configuration.
  set(CMAKE_USER_MAKE_RULES_OVERRIDE "${CMAKE_CURRENT_LIST_DIR}/emscripten-rules.cmake")
  include("${CMAKE_USER_MAKE_RULES_OVERRIDE}")
  list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES FOUNDATION_SDK_ROOT)
  return()
elseif(NOT _system STREQUAL "Linux")
  message(FATAL_ERROR "Use the native Windows compiler with its verified dependency group")
endif()
foreach(_key sysroot cxx_compiler)
  if(IS_ABSOLUTE "${_${_key}}" OR "${_${_key}}" MATCHES "(^|/)\\.\\.(/|$)")
    message(FATAL_ERROR "SDK paths must remain relative to the SDK")
  endif()
  file(REAL_PATH "${FOUNDATION_SDK_ROOT}/${_${_key}}" _resolved)
  cmake_path(IS_PREFIX FOUNDATION_SDK_ROOT "${_resolved}" NORMALIZE _inside)
  if(NOT _inside OR NOT EXISTS "${_resolved}")
    message(FATAL_ERROR "Missing or escaped SDK path")
  endif()
  set(_${_key} "${_resolved}")
endforeach()
set(CMAKE_SYSTEM_NAME "${_system}")
set(CMAKE_SYSTEM_PROCESSOR "${_processor}")
set(CMAKE_CXX_COMPILER "${_cxx_compiler}")
set(CMAKE_SYSROOT "${_sysroot}")
set(CMAKE_FIND_ROOT_PATH "${CMAKE_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_FIND_USE_PACKAGE_REGISTRY OFF)
set(CMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY OFF)
list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES FOUNDATION_SDK_ROOT)

set(ENV{PKG_CONFIG_SYSROOT_DIR} "${CMAKE_SYSROOT}")
set(ENV{PKG_CONFIG_PATH} "")
string(JSON _triple GET "${_sdk}" target triple)
set(ENV{PKG_CONFIG_LIBDIR} "${CMAKE_SYSROOT}/usr/lib/${_triple}/pkgconfig:${CMAKE_SYSROOT}/usr/lib/pkgconfig:${CMAKE_SYSROOT}/usr/share/pkgconfig")
