include_guard(GLOBAL)
# Reused from a standalone component, tooling and allowed source paths still
# belong to the repository containing this policy; an SDK cannot widen them.
get_filename_component(FOUNDATION_POLICY_SOURCE_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." REALPATH)
include("${CMAKE_CURRENT_LIST_DIR}/DependencyPaths.cmake")
set(FOUNDATION_DEPENDENCY_PREFIX "" CACHE PATH "Explicit verified rootless native development tree")
if(FOUNDATION_DEPENDENCY_PREFIX)
  if(FOUNDATION_SDK_ROOT OR FOUNDATION_WINDOWS_DEPENDENCIES OR CMAKE_CROSSCOMPILING OR NOT CMAKE_SYSTEM_NAME STREQUAL "Linux")
    message(FATAL_ERROR "Native development prefixes cannot be combined with a target SDK")
  endif()
  find_package(Python3 3.9 REQUIRED COMPONENTS Interpreter)
  execute_process(COMMAND "${Python3_EXECUTABLE}" -B "${FOUNDATION_POLICY_SOURCE_ROOT}/tools/prepare_dependencies.py" verify "${FOUNDATION_DEPENDENCY_PREFIX}"
    COMMAND_ERROR_IS_FATAL ANY OUTPUT_VARIABLE prefix_identity)
  string(JSON prefix_sha256 GET "${prefix_identity}" sha256)
  if(DEFINED FOUNDATION_CONFIGURED_DEPENDENCY_SHA256 AND NOT FOUNDATION_CONFIGURED_DEPENDENCY_SHA256 STREQUAL prefix_sha256)
    message(FATAL_ERROR "Development prefix identity changed; configure a fresh build directory")
  endif()
  set(FOUNDATION_CONFIGURED_DEPENDENCY_SHA256 "${prefix_sha256}" CACHE INTERNAL "Configured native dependency bytes" FORCE)
  list(PREPEND CMAKE_PREFIX_PATH "${FOUNDATION_DEPENDENCY_PREFIX}/usr")
  # Older distro package configs can retain /usr/include. This native-only
  # overlay uses the verified headers before the host defaults; SDKs cannot mix.
  include_directories(SYSTEM "${FOUNDATION_DEPENDENCY_PREFIX}/usr/include")
  if(CMAKE_LIBRARY_ARCHITECTURE AND IS_DIRECTORY "${FOUNDATION_DEPENDENCY_PREFIX}/usr/include/${CMAKE_LIBRARY_ARCHITECTURE}")
    include_directories(SYSTEM "${FOUNDATION_DEPENDENCY_PREFIX}/usr/include/${CMAKE_LIBRARY_ARCHITECTURE}")
  endif()
endif()
if(DEFINED FOUNDATION_CONFIGURED_DEPENDENCY_PREFIX AND NOT FOUNDATION_CONFIGURED_DEPENDENCY_PREFIX STREQUAL FOUNDATION_DEPENDENCY_PREFIX)
  message(FATAL_ERROR "Development prefix changed; configure a fresh build directory")
endif()
set(FOUNDATION_CONFIGURED_DEPENDENCY_PREFIX "${FOUNDATION_DEPENDENCY_PREFIX}" CACHE INTERNAL "Configured native dependency input" FORCE)
option(FOUNDATION_COMPILER_CACHE "Use an available ccache without requiring it" ON)
if(FOUNDATION_COMPILER_CACHE AND CMAKE_GENERATOR MATCHES "Ninja|Makefiles")
  find_program(FOUNDATION_CCACHE_PROGRAM NAMES ccache NO_CMAKE_FIND_ROOT_PATH)
  if(FOUNDATION_CCACHE_PROGRAM)
    foreach(language C CXX)
      if(NOT CMAKE_${language}_COMPILER_LAUNCHER)
        set(CMAKE_${language}_COMPILER_LAUNCHER "${FOUNDATION_CCACHE_PROGRAM}")
      endif()
    endforeach()
  endif()
endif()

function(foundation_notice_file path)
  if(NOT IS_ABSOLUTE "${path}" OR NOT EXISTS "${path}" OR IS_DIRECTORY "${path}")
    message(FATAL_ERROR "A dependency notice must be an existing absolute file: ${path}")
  endif()
  file(SHA256 "${path}" identity)
  set_property(GLOBAL APPEND PROPERTY FOUNDATION_NOTICE_FILES "${path}")
  set_property(GLOBAL APPEND PROPERTY FOUNDATION_NOTICE_HASHES "${identity}")
endfunction()

function(foundation_generated_application_archive target producer)
  get_target_property(imported "${target}" IMPORTED)
  get_target_property(type "${target}" TYPE)
  get_target_property(producer_type "${producer}" TYPE)
  get_target_property(dependencies "${target}" MANUALLY_ADDED_DEPENDENCIES)
  if(NOT imported OR NOT type STREQUAL "STATIC_LIBRARY" OR
      NOT producer_type STREQUAL "UTILITY" OR NOT producer IN_LIST dependencies)
    message(FATAL_ERROR "A generated application archive requires an imported static target and its utility producer")
  endif()
  get_target_property(configurations "${target}" IMPORTED_CONFIGURATIONS)
  get_target_property(receipts "${target}" FOUNDATION_GENERATED_RECEIPTS)
  get_target_property(inputs "${target}" FOUNDATION_GENERATED_INPUTS)
  get_target_property(verifier "${target}" FOUNDATION_GENERATED_VERIFIER)
  if(NOT configurations OR NOT receipts OR NOT inputs OR NOT verifier)
    message(FATAL_ERROR "A generated application archive requires declared configurations, inputs, receipts and verifier")
  endif()
  set(FOUNDATION_DEPENDENCY_BUILD "${CMAKE_BINARY_DIR}")
  foreach(configuration IN LISTS configurations)
    string(TOUPPER "${configuration}" upper)
    get_target_property(archive "${target}" "IMPORTED_LOCATION_${upper}")
    if(NOT IS_ABSOLUTE "${archive}" OR archive MATCHES "\\$<" OR
        NOT archive MATCHES "\\.(a|lib)$")
      message(FATAL_ERROR "Generated application archive must have an exact per-configuration path: ${archive}")
    endif()
    set(FOUNDATION_DEPENDENCY_GENERATED_ARCHIVES "${archive}")
    foundation_is_generated_dependency("${archive}" checked)
    set_property(GLOBAL APPEND PROPERTY FOUNDATION_GENERATED_ARCHIVES "${archive}")
  endforeach()
  set_property(TARGET "${target}" PROPERTY FOUNDATION_GENERATED_APPLICATION_ARCHIVE TRUE)
  set_property(GLOBAL APPEND PROPERTY FOUNDATION_GENERATED_TARGETS "${target}")
  set_property(GLOBAL APPEND PROPERTY FOUNDATION_GENERATED_PRODUCERS "${producer}")
endfunction()

# Call this at the beginning of every target-bearing subdirectory. A final
# completeness check rejects an unregistered directory rather than losing local
# imported targets, which are deliberately invisible to the parent directory.
function(foundation_register_build_directory)
  get_property(registered DIRECTORY PROPERTY FOUNDATION_POLICY_REGISTERED)
  if(registered)
    return()
  endif()
  set_property(DIRECTORY PROPERTY FOUNDATION_POLICY_REGISTERED TRUE)
  cmake_language(DEFER CALL _foundation_capture_directory_policy)
endfunction()

# A retained dependency with its own project() receives the same scoped guard
# without editing supplier source. Preserve any existing project hooks.
set(foundation_directory_hook "${CMAKE_BINARY_DIR}/foundation-register-directory.cmake")
file(WRITE "${foundation_directory_hook}" "foundation_register_build_directory()\n")
list(APPEND CMAKE_PROJECT_INCLUDE_BEFORE "${foundation_directory_hook}")

function(_foundation_capture_directory_policy)
  get_property(captured DIRECTORY PROPERTY FOUNDATION_POLICY_CAPTURED)
  if(captured)
    return()
  endif()
  set_property(DIRECTORY PROPERTY FOUNDATION_POLICY_CAPTURED TRUE)
  get_property(targets DIRECTORY PROPERTY BUILDSYSTEM_TARGETS)
  get_property(imported_targets DIRECTORY PROPERTY IMPORTED_TARGETS)
  list(APPEND targets ${imported_targets})
  string(SHA256 directory_id "${CMAKE_CURRENT_SOURCE_DIR}")
  set(notices "")
  get_property(generated_targets GLOBAL PROPERTY FOUNDATION_GENERATED_TARGETS)
  if(FOUNDATION_GUI_DISTRIBUTABLE AND NOT FOUNDATION_SDK_ROOT AND NOT FOUNDATION_WINDOWS_DEPENDENCIES)
    foreach(target IN LISTS imported_targets)
      get_target_property(type "${target}" TYPE)
      if(type MATCHES "^(STATIC_LIBRARY|SHARED_LIBRARY|UNKNOWN_LIBRARY)$" AND NOT target IN_LIST generated_targets)
        string(APPEND notices "list(APPEND command --library [==[$<TARGET_FILE:${target}>]==])\n")
      endif()
    endforeach()
  endif()
  set(notice_fragment "${CMAKE_BINARY_DIR}/policy/${directory_id}-notices-$<CONFIG>.cmake")
  file(GENERATE OUTPUT "${notice_fragment}" CONTENT "${notices}")
  set_property(GLOBAL APPEND PROPERTY FOUNDATION_NOTICE_FRAGMENTS "${notice_fragment}")
  if(FOUNDATION_SDK_ROOT AND CMAKE_SYSTEM_NAME STREQUAL "Linux")
    set(FOUNDATION_DEPENDENCY_SYSROOT "${CMAKE_SYSROOT}")
    # The component owns its sources; shared declarations live in this fixed
    # repository. Neither root permits foreign dependency libraries.
    set(FOUNDATION_DEPENDENCY_SOURCE "${CMAKE_SOURCE_DIR}" "${FOUNDATION_POLICY_SOURCE_ROOT}")
    list(REMOVE_DUPLICATES FOUNDATION_DEPENDENCY_SOURCE)
    set(FOUNDATION_DEPENDENCY_BUILD "${CMAKE_BINARY_DIR}")
    set(FOUNDATION_DEPENDENCY_GUI "${FOUNDATION_GUI_SOURCE}")
    get_property(FOUNDATION_DEPENDENCY_GENERATED_ARCHIVES GLOBAL PROPERTY FOUNDATION_GENERATED_ARCHIVES)
    get_property(generated_targets GLOBAL PROPERTY FOUNDATION_GENERATED_TARGETS)
    set(check "include([==[${CMAKE_CURRENT_FUNCTION_LIST_DIR}/DependencyPaths.cmake]==])\n")
    foreach(name SYSROOT SOURCE BUILD GUI)
      string(APPEND check "set(FOUNDATION_DEPENDENCY_${name} [==[${FOUNDATION_DEPENDENCY_${name}}]==])\n")
    endforeach()
    string(APPEND check "set(FOUNDATION_DEPENDENCY_GENERATED_ARCHIVES)\n")
    foreach(generated_target IN LISTS generated_targets)
      string(APPEND check "list(APPEND FOUNDATION_DEPENDENCY_GENERATED_ARCHIVES [==[$<TARGET_FILE:${generated_target}>]==])\n")
    endforeach()
    get_property(enabled_languages GLOBAL PROPERTY ENABLED_LANGUAGES)
    if(FOUNDATION_VERIFY_SDK AND "C" IN_LIST enabled_languages)
      file(READ "${FOUNDATION_SDK_ROOT}/sdk.json" sdk_metadata)
      string(JSON declared_c ERROR_VARIABLE c_error GET "${sdk_metadata}" target c_compiler)
      if(c_error)
        message(FATAL_ERROR "The selected SDK has no declared C compiler")
      endif()
      file(REAL_PATH "${FOUNDATION_SDK_ROOT}/${declared_c}" expected_c)
      file(REAL_PATH "${CMAKE_C_COMPILER}" actual_c)
      if(NOT actual_c STREQUAL expected_c)
        message(FATAL_ERROR "C compiler differs from the selected SDK")
      endif()
    endif()
    foreach(kind EXE SHARED MODULE STATIC)
      foreach(suffix "" _DEBUG _RELEASE _RELWITHDEBINFO _MINSIZEREL)
        if(CMAKE_${kind}_LINKER_FLAGS${suffix} MATCHES "(^|[ ;,:])(-L|--library-path|--sysroot)")
          message(FATAL_ERROR "SDK linker search overrides are unsupported; use verified targets")
        endif()
      endforeach()
    endforeach()
    foreach(language C CXX)
      foreach(suffix "" _DEBUG _RELEASE _RELWITHDEBINFO _MINSIZEREL)
        if(CMAKE_${language}_FLAGS${suffix} MATCHES "(^|[ ;])(-I|-L|-isystem|-iquote|--sysroot|/I)")
          message(FATAL_ERROR "SDK include/library search overrides are unsupported; use verified targets")
        endif()
      endforeach()
    endforeach()
    foreach(target IN LISTS targets)
      get_target_property(type "${target}" TYPE)
      get_target_property(imported "${target}" IMPORTED)
      if(imported AND NOT type STREQUAL "EXECUTABLE")
        get_target_property(configurations "${target}" IMPORTED_CONFIGURATIONS)
        set(properties IMPORTED_LOCATION IMPORTED_IMPLIB)
        foreach(configuration IN LISTS configurations CMAKE_CONFIGURATION_TYPES)
          string(TOUPPER "${configuration}" configuration)
          list(APPEND properties "IMPORTED_LOCATION_${configuration}" "IMPORTED_IMPLIB_${configuration}")
        endforeach()
        list(APPEND properties IMPORTED_LOCATION_DEBUG IMPORTED_LOCATION_RELEASE IMPORTED_LOCATION_RELWITHDEBINFO IMPORTED_LOCATION_MINSIZEREL)
        foreach(property IN LISTS properties)
          get_target_property(value "${target}" "${property}")
          if(value AND NOT value MATCHES "\\$<")
            foundation_check_dependency(library "${value}")
            foundation_is_generated_dependency("${value}" generated)
            if(NOT generated)
              file(SHA256 "${value}" identity)
              string(APPEND check "foundation_check_dependency_hash([==[${value}]==] ${identity})\n")
            endif()
          endif()
        endforeach()
      endif()
      foreach(property COMPILE_OPTIONS INTERFACE_COMPILE_OPTIONS LINK_OPTIONS INTERFACE_LINK_OPTIONS)
        get_target_property(options "${target}" "${property}")
        if(options AND options MATCHES "(^|[ ;,:>])(-I|-L|-isystem|-iquote|-idirafter|--library-path|--sysroot)")
          message(FATAL_ERROR "SDK target search overrides are unsupported; use include and link target properties")
        endif()
      endforeach()
      foreach(property INCLUDE_DIRECTORIES INTERFACE_INCLUDE_DIRECTORIES INTERFACE_SYSTEM_INCLUDE_DIRECTORIES LINK_DIRECTORIES INTERFACE_LINK_DIRECTORIES LINK_LIBRARIES INTERFACE_LINK_LIBRARIES)
        get_target_property(values "${target}" "${property}")
        if(NOT values)
          continue()
        endif()
        if(property MATCHES "INCLUDE")
          set(kind include)
        else()
          set(kind library)
        endif()
        foreach(value IN LISTS values)
          if(NOT value MATCHES "\\$<")
            foundation_check_dependency_values("${kind}" "${value}")
            if(kind STREQUAL "library" AND IS_ABSOLUTE "${value}" AND NOT IS_DIRECTORY "${value}")
              foundation_is_generated_dependency("${value}" generated)
              if(NOT generated)
                file(SHA256 "${value}" identity)
                string(APPEND check "foundation_check_dependency_hash([==[${value}]==] ${identity})\n")
              endif()
            endif()
          endif()
        endforeach()
        string(APPEND check "foundation_check_dependency_values(${kind} [==[$<TARGET_GENEX_EVAL:${target},$<TARGET_PROPERTY:${target},${property}>>]==])\n")
      endforeach()
    endforeach()
    set(check_file "${CMAKE_BINARY_DIR}/policy/${directory_id}-dependencies-$<CONFIG>.cmake")
    file(GENERATE OUTPUT "${check_file}" CONTENT "${check}")
    set_property(GLOBAL APPEND PROPERTY FOUNDATION_DEPENDENCY_FRAGMENTS "${check_file}")
  endif()
endfunction()

function(_foundation_directory_targets directory output)
  get_property(targets DIRECTORY "${directory}" PROPERTY BUILDSYSTEM_TARGETS)
  get_property(imported DIRECTORY "${directory}" PROPERTY IMPORTED_TARGETS)
  get_property(registered DIRECTORY "${directory}" PROPERTY FOUNDATION_POLICY_REGISTERED)
  if((targets OR imported) AND NOT registered)
    message(FATAL_ERROR "Target directory must call foundation_register_build_directory(): ${directory}")
  endif()
  get_property(children DIRECTORY "${directory}" PROPERTY SUBDIRECTORIES)
  foreach(child IN LISTS children)
    _foundation_directory_targets("${child}" nested)
    list(APPEND targets ${nested})
  endforeach()
  set(${output} "${targets}" PARENT_SCOPE)
endfunction()

function(foundation_finalize_build_policy)
  cmake_parse_arguments(policy "NO_INSTALL" "" "" ${ARGN})
  if(policy_UNPARSED_ARGUMENTS)
    message(FATAL_ERROR "Unknown build policy option: ${policy_UNPARSED_ARGUMENTS}")
  endif()
  _foundation_capture_directory_policy()
  set(FOUNDATION_NOTICE_MANIFEST "" CACHE FILEPATH "Reviewed hash-bound notices for dependencies without distro ownership")
  _foundation_directory_targets("${CMAKE_SOURCE_DIR}" targets)
  list(REMOVE_DUPLICATES targets)
  if(NOT policy_NO_INSTALL)
    set(notice_command "set(command [==[${Python3_EXECUTABLE}]==] [==[${FOUNDATION_POLICY_SOURCE_ROOT}/tools/package_notices.py]==] --output \"\$ENV{DESTDIR}\${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_DOCDIR}/dependency-notices\")\n")
    if(FOUNDATION_SDK_ROOT)
      string(APPEND notice_command "list(APPEND command --sdk [==[${FOUNDATION_SDK_ROOT}]==])\n")
    elseif(FOUNDATION_WINDOWS_DEPENDENCIES)
      string(APPEND notice_command "list(APPEND command --windows-dependencies [==[${FOUNDATION_WINDOWS_DEPENDENCIES}]==])\n")
    endif()
    if(FOUNDATION_NOTICE_MANIFEST)
      string(APPEND notice_command "list(APPEND command --manifest [==[${FOUNDATION_NOTICE_MANIFEST}]==])\n")
    endif()
    if(FOUNDATION_PORTABLE AND CMAKE_SYSTEM_NAME STREQUAL "Linux")
      string(APPEND notice_command "list(APPEND command --runtime-inventory \"\$ENV{DESTDIR}\${CMAKE_INSTALL_PREFIX}/lib/runtime/runtime-inventory.json\")\n")
      foreach(root IN LISTS FOUNDATION_RUNTIME_ROOTS)
        string(APPEND notice_command "list(APPEND command --runtime-root [==[${root}]==])\n")
      endforeach()
    endif()
    get_property(notices GLOBAL PROPERTY FOUNDATION_NOTICE_FILES)
    get_property(hashes GLOBAL PROPERTY FOUNDATION_NOTICE_HASHES)
    list(LENGTH notices count)
    if(count GREATER 0)
      math(EXPR last "${count}-1")
      foreach(index RANGE 0 ${last})
        list(GET notices ${index} notice)
        list(GET hashes ${index} identity)
        string(APPEND notice_command "list(APPEND command --file [==[${notice}]==] ${identity})\n")
      endforeach()
    endif()
    if(NOT FOUNDATION_SDK_ROOT AND NOT FOUNDATION_WINDOWS_DEPENDENCIES)
      if(FOUNDATION_PORTABLE AND CMAKE_SYSTEM_NAME STREQUAL "Linux")
        foreach(name libstdc++.a libgcc.a libgcc_eh.a)
          execute_process(COMMAND "${CMAKE_CXX_COMPILER}" "-print-file-name=${name}"
            OUTPUT_VARIABLE library OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
          if(NOT IS_ABSOLUTE "${library}" OR NOT EXISTS "${library}")
            message(FATAL_ERROR "Cannot identify selected static runtime: ${name}")
          endif()
          string(APPEND notice_command "list(APPEND command --library [==[${library}]==])\n")
        endforeach()
      endif()
      get_property(fragments GLOBAL PROPERTY FOUNDATION_NOTICE_FRAGMENTS)
      foreach(fragment IN LISTS fragments)
        string(APPEND notice_command "include([==[${fragment}]==])\n")
      endforeach()
    endif()
    string(APPEND notice_command "execute_process(COMMAND \${command} RESULT_VARIABLE status)\nif(NOT status EQUAL 0)\n  message(FATAL_ERROR \"Dependency notice staging failed\")\nendif()\n")
    set(notice_script "${CMAKE_BINARY_DIR}/install-notices-$<CONFIG>.cmake")
    file(GENERATE OUTPUT "${notice_script}" CONTENT "${notice_command}")
    install(SCRIPT "${notice_script}")
  endif()
  if(FOUNDATION_DEPENDENCY_PREFIX)
    add_custom_target(foundation-prefix-check ALL COMMAND "${Python3_EXECUTABLE}" -B
      "${FOUNDATION_POLICY_SOURCE_ROOT}/tools/prepare_dependencies.py" verify "${FOUNDATION_DEPENDENCY_PREFIX}" --expected-sha256 "${FOUNDATION_CONFIGURED_DEPENDENCY_SHA256}" VERBATIM)
    foreach(target IN LISTS targets)
      get_target_property(imported "${target}" IMPORTED)
      get_target_property(type "${target}" TYPE)
      if(NOT imported AND NOT type STREQUAL "INTERFACE_LIBRARY" AND NOT type STREQUAL "UTILITY")
        add_dependencies("${target}" foundation-prefix-check)
      endif()
    endforeach()
    if(NOT policy_NO_INSTALL)
      install(CODE "execute_process(COMMAND [==[${Python3_EXECUTABLE}]==] -B [==[${FOUNDATION_POLICY_SOURCE_ROOT}/tools/prepare_dependencies.py]==] verify [==[${FOUNDATION_DEPENDENCY_PREFIX}]==] --expected-sha256 ${FOUNDATION_CONFIGURED_DEPENDENCY_SHA256} COMMAND_ERROR_IS_FATAL ANY)")
    endif()
  endif()
  # Directory fragments were captured where their local imports are visible.
  if(FOUNDATION_SDK_ROOT AND CMAKE_SYSTEM_NAME STREQUAL "Linux")
    set(check "")
    if(FOUNDATION_VERIFY_SDK)
      string(APPEND check "execute_process(COMMAND [==[${Python3_EXECUTABLE}]==] -B [==[${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../tools/sdk_verify.py]==] [==[${FOUNDATION_SDK_ROOT}]==] COMMAND_ERROR_IS_FATAL ANY OUTPUT_QUIET)\n")
    endif()
    get_property(fragments GLOBAL PROPERTY FOUNDATION_DEPENDENCY_FRAGMENTS)
    foreach(fragment IN LISTS fragments)
      string(APPEND check "include([==[${fragment}]==])\n")
    endforeach()
    set(check_file "${CMAKE_BINARY_DIR}/dependency-paths-$<CONFIG>.cmake")
    file(GENERATE OUTPUT "${check_file}" CONTENT "${check}")
    add_custom_target(foundation-dependency-check ALL COMMAND "${CMAKE_COMMAND}" -P "${check_file}" VERBATIM)
    get_property(generated_producers GLOBAL PROPERTY FOUNDATION_GENERATED_PRODUCERS)
    if(generated_producers)
      add_dependencies(foundation-dependency-check ${generated_producers})
    endif()
    foreach(target IN LISTS targets)
      get_target_property(imported "${target}" IMPORTED)
      get_target_property(type "${target}" TYPE)
      if(NOT imported AND NOT type STREQUAL "INTERFACE_LIBRARY" AND NOT type STREQUAL "UTILITY")
        add_dependencies("${target}" foundation-dependency-check)
      endif()
    endforeach()
    if(NOT policy_NO_INSTALL)
      install(SCRIPT "${check_file}")
    endif()
  endif()
endfunction()

foundation_register_build_directory()
