include_guard(GLOBAL)

function(foundation_is_generated_dependency path output)
  set(${output} FALSE PARENT_SCOPE)
  list(FIND FOUNDATION_DEPENDENCY_GENERATED_ARCHIVES "${path}" generated_index)
  if(NOT IS_ABSOLUTE "${path}" OR generated_index LESS 0)
    return()
  endif()
  file(REAL_PATH "${FOUNDATION_DEPENDENCY_BUILD}" build_root)
  set(existing "${path}")
  while(NOT EXISTS "${existing}")
    get_filename_component(existing "${existing}" DIRECTORY)
  endwhile()
  file(REAL_PATH "${existing}" physical_path)
  cmake_path(IS_PREFIX build_root "${physical_path}" NORMALIZE inside)
  if(NOT inside OR IS_DIRECTORY "${path}" OR IS_SYMLINK "${path}")
    message(FATAL_ERROR "Generated application archive escapes its declared build root: ${path}")
  endif()
  set(${output} TRUE PARENT_SCOPE)
endfunction()

# Validate physical paths, not spelling: an in-root alias may name a host file.
function(foundation_check_dependency kind path)
  if(NOT IS_ABSOLUTE "${path}")
    if(kind STREQUAL "include" AND NOT "${path}" STREQUAL "")
      message(FATAL_ERROR "SDK dependency include directory must be absolute: ${path}")
    endif()
    return()
  endif()
  if(kind STREQUAL "library")
    foundation_is_generated_dependency("${path}" generated)
    if(generated)
      return()
    endif()
  endif()
  file(REAL_PATH "${path}" resolved)
  set(roots "${FOUNDATION_DEPENDENCY_SYSROOT}")
  if(kind STREQUAL "include")
    list(APPEND roots "${FOUNDATION_DEPENDENCY_SOURCE}" "${FOUNDATION_DEPENDENCY_BUILD}" "${FOUNDATION_DEPENDENCY_GUI}")
  endif()
  foreach(root IN LISTS roots)
    if(NOT root STREQUAL "")
      file(REAL_PATH "${root}" physical_root)
      cmake_path(IS_PREFIX physical_root "${resolved}" NORMALIZE inside)
      if(inside)
        if(NOT EXISTS "${path}" AND NOT root STREQUAL FOUNDATION_DEPENDENCY_BUILD)
          message(FATAL_ERROR "SDK dependency does not exist: ${path}")
        endif()
        return()
      endif()
    endif()
  endforeach()
  message(FATAL_ERROR "SDK dependency escapes declared roots (${kind}): ${path} -> ${resolved}")
endfunction()

function(foundation_check_dependency_values kind values)
  foreach(value IN LISTS values)
    if(value MATCHES "\\$<")
      message(FATAL_ERROR "Unresolved SDK dependency expression: ${value}")
    endif()
    if(value MATCHES "^-L(.+)$" OR value MATCHES "^-I(.+)$")
      set(value "${CMAKE_MATCH_1}")
    endif()
    if(value STREQUAL "" OR value MATCHES "^::@" OR value MATCHES "-NOTFOUND$")
      continue()
    endif()
    foundation_check_dependency("${kind}" "${value}")
  endforeach()
endfunction()

function(foundation_check_dependency_hash path expected)
  foundation_check_dependency(library "${path}")
  file(SHA256 "${path}" actual)
  if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "Configured SDK library bytes changed: ${path}")
  endif()
endfunction()
