# Shared native GUI toolkit recipes; no product composition roots or installs.
include_guard(GLOBAL)

macro(foundation_gui_native_backend backend)
    if("${backend}" STREQUAL "fltk")
        set(FLTK_SKIP_OPENGL TRUE)
        set(FLTK_SKIP_FORMS TRUE)
        set(FLTK_SKIP_IMAGES TRUE)
        set(FLTK_SKIP_FLUID TRUE)
        find_package(FLTK REQUIRED)
        foundation_gui_patch(backends/fltk/adapter.hpp fltk-appearance.patch patch-inputs/fltk-appearance.hpp)
        foundation_gui_repatch(patch-inputs/fltk-appearance.hpp fltk-pointer.patch patch-inputs/fltk-pointer.hpp)
        foundation_gui_repatch(patch-inputs/fltk-pointer.hpp fltk-service-focus.patch fltk/adapter.hpp)
        add_library(foundation_gui_fltk INTERFACE)
        target_include_directories(foundation_gui_fltk SYSTEM INTERFACE
            "${CMAKE_CURRENT_BINARY_DIR}/fltk" ${FLTK_INCLUDE_DIR})
        target_link_libraries(foundation_gui_fltk INTERFACE ${FLTK_LIBRARIES})
        if(FOUNDATION_SDK_ROOT AND CMAKE_SYSTEM_NAME STREQUAL "Linux")
            # The prepared static FLTK uses Xft; FindFLTK's autotools path does not
            # carry that closure. Xft also imports Xrender, Fontconfig and FreeType.
            find_package(X11 REQUIRED COMPONENTS Xft Xrender)
            target_link_libraries(foundation_gui_fltk INTERFACE X11::Xft)
        endif()
    endif()
    if("${backend}" STREQUAL "sdl")
        find_package(SDL2 CONFIG REQUIRED)
        add_library(foundation_gui_sdl INTERFACE)
        if(TARGET SDL2::SDL2main)
            target_link_libraries(foundation_gui_sdl INTERFACE SDL2::SDL2main)
        endif()
        if(FOUNDATION_PORTABLE)
            if(NOT TARGET SDL2::SDL2-static)
                message(FATAL_ERROR "Portable SDL requires the retained SDL2::SDL2-static target")
            endif()
            target_link_libraries(foundation_gui_sdl INTERFACE SDL2::SDL2-static)
        else()
            target_link_libraries(foundation_gui_sdl INTERFACE SDL2::SDL2)
        endif()
        foundation_gui_patch(backends/framebuffer/main_sdl.cpp sdl-runner.patch sdl_runner.hpp)
    endif()
    if("${backend}" STREQUAL "rev")
        if(FOUNDATION_SDK_ROOT)
            # Prepared GUI SDKs supply platform libraries; the retained GUI input
            # supplies the exact GLEW/FreeType sources. Never search the host for them.
            if(DEFINED GUI_REV_BUNDLED_DEPS AND NOT GUI_REV_BUNDLED_DEPS)
                message(FATAL_ERROR "Prepared SDK Rev requires GUI_REV_BUNDLED_DEPS=ON")
            endif()
            set(GUI_REV_BUNDLED_DEPS ON CACHE BOOL "Build preserved local GLEW/FreeType sources")
        endif()
        foundation_gui_patch(cmake/GuiRev.cmake rev-build.patch Rev.cmake)
        foundation_gui_patch(cmake/RevDependencies.cmake rev-dependencies.patch RevDependencies.cmake)
        foundation_gui_patch(backends/rev/adapter.cpp rev-pointer.patch rev/adapter.cpp)
        foundation_gui_patch(backends/rev/probe.hpp rev-pointer-probe.patch rev/probe.hpp)
        include("${CMAKE_CURRENT_BINARY_DIR}/Rev.cmake")
    endif()
endmacro()
