include_guard(GLOBAL)

set(FOUNDATION_RUST_SDK_ROOT "" CACHE PATH "Verified retained Rust extension SDK")
set(FOUNDATION_RUST_TARGET "" CACHE STRING "Explicit Rust target triple, or the matching platform default")

function(foundation_rust_component core)
  foreach(field SDK_RECIPE_ID SDK_MANIFEST_SHA256 COMPILER_VERSION COMPILER_SHA256 SELECTED_TARGET)
    set(FOUNDATION_RUST_${field} none PARENT_SCOPE)
  endforeach()
  if(NOT FOUNDATION_CORE_PROVIDER STREQUAL "rust")
    return()
  endif()
  if(CMAKE_INTERPROCEDURAL_OPTIMIZATION)
    message(FATAL_ERROR "The Rust component uses native objects without cross-language LTO")
  endif()
  if(EMSCRIPTEN)
    set(default_target wasm32-unknown-emscripten)
  elseif(CMAKE_SYSTEM_NAME STREQUAL "Windows" AND MSVC AND CMAKE_SIZEOF_VOID_P EQUAL 8)
    if(NOT CMAKE_CXX_COMPILER_ARCHITECTURE_ID MATCHES "ARM64" AND
        NOT CMAKE_GENERATOR_PLATFORM MATCHES "ARM64" AND
        CMAKE_SYSTEM_PROCESSOR MATCHES "^(x86_64|AMD64|amd64)$")
      set(default_target x86_64-pc-windows-msvc)
    endif()
  elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    if(CMAKE_SYSTEM_PROCESSOR MATCHES "^(x86_64|AMD64|amd64)$")
      set(default_target x86_64-unknown-linux-gnu)
    elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "^(aarch64|arm64|ARM64)$")
      set(default_target aarch64-unknown-linux-gnu)
    endif()
  endif()
  if(NOT default_target)
    message(FATAL_ERROR "The Rust provider requires a declared Linux GNU, Windows x64 MSVC or Emscripten target; use FOUNDATION_CORE_PROVIDER=cpp for this platform")
  endif()
  if(FOUNDATION_RUST_TARGET AND NOT FOUNDATION_RUST_TARGET STREQUAL default_target)
    message(FATAL_ERROR "Rust target does not match the selected C++ target: ${FOUNDATION_RUST_TARGET} != ${default_target}")
  endif()
  set(target "${default_target}")
  set(sdk_recipe none)
  set(sdk_sha256 none)
  set(sdk_arguments)
  set(cpp_sdk "${FOUNDATION_SDK_ROOT}")
  if(NOT cpp_sdk AND FOUNDATION_WINDOWS_DEPENDENCIES)
    set(cpp_sdk "${FOUNDATION_WINDOWS_DEPENDENCIES}")
  endif()
  if(FOUNDATION_RUST_SDK_ROOT)
    set(verify_command "${Python3_EXECUTABLE}" -B "${CMAKE_SOURCE_DIR}/tools/rust_sdk.py"
      verify --root "${FOUNDATION_RUST_SDK_ROOT}" --target "${target}")
    if(cpp_sdk)
      list(APPEND verify_command --cpp-sdk "${cpp_sdk}")
    endif()
    execute_process(COMMAND ${verify_command} OUTPUT_VARIABLE sdk
      COMMAND_ERROR_IS_FATAL ANY OUTPUT_STRIP_TRAILING_WHITESPACE)
    string(JSON rustc GET "${sdk}" rustc)
    string(JSON cargo GET "${sdk}" cargo)
    string(JSON sdk_recipe GET "${sdk}" metadata recipe_id)
    string(JSON sdk_sha256 GET "${sdk}" sha256)
    list(APPEND sdk_arguments --sdk-root "${FOUNDATION_RUST_SDK_ROOT}")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${FOUNDATION_RUST_SDK_ROOT}/rust-sdk.json")
  else()
    if(NOT CMAKE_SYSTEM_NAME STREQUAL "Linux" OR CMAKE_CROSSCOMPILING OR cpp_sdk)
      message(FATAL_ERROR "This Rust target requires FOUNDATION_RUST_SDK_ROOT; native Linux distribution tools are available only without a target SDK")
    endif()
    find_program(FOUNDATION_RUST_RUSTC NAMES rustc NO_CMAKE_FIND_ROOT_PATH)
    find_program(FOUNDATION_RUST_CARGO NAMES cargo NO_CMAKE_FIND_ROOT_PATH)
    if(NOT FOUNDATION_RUST_RUSTC OR NOT FOUNDATION_RUST_CARGO)
      message(FATAL_ERROR "Rust provider explicitly selected but rustc/Cargo are missing; provide a retained FOUNDATION_RUST_SDK_ROOT or native distribution tools")
    endif()
    set(rustc "${FOUNDATION_RUST_RUSTC}")
    set(cargo "${FOUNDATION_RUST_CARGO}")
  endif()
  if(cpp_sdk)
    list(APPEND sdk_arguments --cpp-sdk-root "${cpp_sdk}")
  endif()
  if(CMAKE_CONFIGURATION_TYPES)
    set(configurations ${CMAKE_CONFIGURATION_TYPES})
  elseif(CMAKE_BUILD_TYPE)
    set(configurations "${CMAKE_BUILD_TYPE}")
  else()
    set(configurations NoConfig)
  endif()
  add_library(foundation::rust_component STATIC IMPORTED)
  set(receipts)
  set(byproducts)
  set(all_inputs)
  set(native_libraries)
  foreach(configuration IN LISTS configurations)
    string(TOLOWER "${configuration}" profile)
    if(NOT profile STREQUAL "debug")
      set(profile release)
    endif()
    set(config_file "${CMAKE_BINARY_DIR}/rust/${configuration}/config.json")
    execute_process(COMMAND "${Python3_EXECUTABLE}" -B "${CMAKE_SOURCE_DIR}/tools/rust_build.py"
      describe --source-root "${CMAKE_SOURCE_DIR}" --build-dir "${CMAKE_BINARY_DIR}/rust/${configuration}"
      --target "${target}" --cargo "${cargo}" --rustc "${rustc}" --profile "${profile}"
      ${sdk_arguments} --output "${config_file}" COMMAND_ERROR_IS_FATAL ANY)
    file(READ "${config_file}" description)
    string(JSON archive GET "${description}" artifact_path)
    string(JSON receipt GET "${description}" receipt_path)
    string(JSON compiler_version GET "${description}" tools rustc version)
    string(JSON compiler_host GET "${description}" tools rustc host)
    string(JSON compiler_sha256 GET "${description}" tools rustc sha256)
    string(JSON cargo_sha256 GET "${description}" tools cargo sha256)
    string(TOUPPER "${configuration}" upper)
    set_property(TARGET foundation::rust_component APPEND PROPERTY IMPORTED_CONFIGURATIONS "${configuration}")
    set_property(TARGET foundation::rust_component PROPERTY "IMPORTED_LOCATION_${upper}" "${archive}")
    list(APPEND receipts "${receipt}")
    if(configuration STREQUAL "NoConfig")
      set(config_expression "")
    else()
      set(config_expression "${configuration}")
    endif()
    list(APPEND byproducts "$<$<CONFIG:${config_expression}>:${archive}>" "$<$<CONFIG:${config_expression}>:${receipt}>")
    get_filename_component(archive_name "${archive}" NAME)
    foreach(field source_inputs native_static_libs notice_files)
      string(JSON count LENGTH "${description}" "${field}")
      set(values)
      if(count GREATER 0)
        math(EXPR last "${count}-1")
        foreach(index RANGE 0 ${last})
          string(JSON value GET "${description}" "${field}" ${index})
          list(APPEND values "${value}")
        endforeach()
      endif()
      if(field STREQUAL "source_inputs")
        list(APPEND all_inputs ${values})
      elseif(field STREQUAL "notice_files")
        foreach(notice IN LISTS values)
          foundation_notice_file("${notice}")
        endforeach()
      elseif(native_libraries AND NOT native_libraries STREQUAL values)
        message(FATAL_ERROR "Rust native library requirements differ between configurations")
      else()
        set(native_libraries "${values}")
      endif()
    endforeach()
  endforeach()
  set(identity "${target};${rustc};${cargo};${compiler_sha256};${cargo_sha256};${sdk_sha256}")
  string(SHA256 identity "${identity}")
  if(DEFINED FOUNDATION_CONFIGURED_RUST_IDENTITY AND NOT FOUNDATION_CONFIGURED_RUST_IDENTITY STREQUAL identity)
    message(FATAL_ERROR "Rust toolchain identity changed; configure a fresh build directory")
  endif()
  set(FOUNDATION_CONFIGURED_RUST_IDENTITY "${identity}" CACHE INTERNAL "Configured Rust toolchain" FORCE)
  file(GLOB_RECURSE rust_inputs CONFIGURE_DEPENDS
    "${CMAKE_SOURCE_DIR}/rust/*.rs" "${CMAKE_SOURCE_DIR}/rust/*.toml" "${CMAKE_SOURCE_DIR}/rust/Cargo.lock")
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${all_inputs} ${rust_inputs}
    "${CMAKE_SOURCE_DIR}/tools/rust_build.py" "${CMAKE_SOURCE_DIR}/tools/rust_sdk.py")
  set(selected_configuration "$<IF:$<BOOL:$<CONFIG>>,$<CONFIG>,NoConfig>")
  set(selected_config "${CMAKE_BINARY_DIR}/rust/${selected_configuration}/config.json")
  set(selected_archive "$<TARGET_FILE:foundation::rust_component>")
  add_custom_target(foundation-rust
    COMMAND "${Python3_EXECUTABLE}" -B "${CMAKE_SOURCE_DIR}/tools/rust_build.py" build --config "${selected_config}"
    COMMAND "${Python3_EXECUTABLE}" -B "${CMAKE_SOURCE_DIR}/tools/rust_build.py" verify --config "${selected_config}"
    BYPRODUCTS ${byproducts}
    VERBATIM)
  add_dependencies(foundation::rust_component foundation-rust)
  if(BUILD_TESTING AND NOT EMSCRIPTEN AND compiler_host STREQUAL target)
    add_test(NAME rust.unit COMMAND "${Python3_EXECUTABLE}" -B "${CMAKE_SOURCE_DIR}/tools/rust_build.py"
      test --config "${selected_config}")
    set_tests_properties(rust.unit PROPERTIES LABELS "rust;unit" TIMEOUT 180 RESOURCE_LOCK rust-build)
    foundation_test_prerequisites(rust.unit foundation-rust)
  endif()
  set_target_properties(foundation::rust_component PROPERTIES
    FOUNDATION_GENERATED_RECEIPTS "${receipts}" FOUNDATION_GENERATED_INPUTS "${all_inputs}"
    FOUNDATION_GENERATED_VERIFIER "${Python3_EXECUTABLE};-B;${CMAKE_SOURCE_DIR}/tools/rust_build.py;verify;--config;${selected_config}"
    INTERFACE_LINK_LIBRARIES "${native_libraries}")
  set(link_options)
  if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    list(APPEND link_options "LINKER:--exclude-libs,${archive_name}")
    set_property(TARGET foundation::rust_component PROPERTY INTERFACE_LINK_OPTIONS "${link_options}")
  endif()
  foundation_generated_application_archive(foundation::rust_component foundation-rust)
  target_compile_definitions(${core} PRIVATE FOUNDATION_USE_RUST=1)
  target_link_libraries(${core} PRIVATE foundation::rust_component)
  set(install_script "include([==[${CMAKE_CURRENT_FUNCTION_LIST_DIR}/DependencyPaths.cmake]==])\nset(FOUNDATION_DEPENDENCY_BUILD [==[${CMAKE_BINARY_DIR}]==])\nset(FOUNDATION_DEPENDENCY_GENERATED_ARCHIVES [==[${selected_archive}]==])\nfoundation_check_dependency(library [==[${selected_archive}]==])\nexecute_process(COMMAND [==[${Python3_EXECUTABLE}]==] -B [==[${CMAKE_SOURCE_DIR}/tools/rust_build.py]==] verify --config [==[${selected_config}]==] COMMAND_ERROR_IS_FATAL ANY)\nfile(INSTALL DESTINATION \"\$ENV{DESTDIR}\${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR}\" TYPE FILE FILES [==[${selected_archive}]==])\n")
  file(GENERATE OUTPUT "${CMAKE_BINARY_DIR}/install-rust-$<CONFIG>.cmake" CONTENT "${install_script}")
  install(SCRIPT "${CMAKE_BINARY_DIR}/install-rust-$<CONFIG>.cmake")
  set(FOUNDATION_RUST_ARCHIVE_NAME "${archive_name}" PARENT_SCOPE)
  set(FOUNDATION_RUST_NATIVE_LIBRARIES "${native_libraries}" PARENT_SCOPE)
  set(FOUNDATION_RUST_LINK_OPTIONS "${link_options}" PARENT_SCOPE)
  set(FOUNDATION_RUST_SDK_RECIPE_ID "${sdk_recipe}" PARENT_SCOPE)
  set(FOUNDATION_RUST_SDK_MANIFEST_SHA256 "${sdk_sha256}" PARENT_SCOPE)
  set(FOUNDATION_RUST_COMPILER_VERSION "${compiler_version}" PARENT_SCOPE)
  set(FOUNDATION_RUST_COMPILER_SHA256 "${compiler_sha256}" PARENT_SCOPE)
  set(FOUNDATION_RUST_SELECTED_TARGET "${target}" PARENT_SCOPE)
endfunction()
