include_guard(GLOBAL)

# Register every test explicitly, including scripts with no compiled prerequisites.
# Labels select local development groups; candidate ownership is independently
# derived from the complete inventory by test_plan.py.
function(foundation_test_prerequisites name)
  if(NOT TEST "${name}" OR NOT name MATCHES "^[A-Za-z0-9_][A-Za-z0-9_.+-]*$")
    message(FATAL_ERROR "Register an existing, safely named test: ${name}")
  endif()
  string(SHA256 key "${name}")
  get_property(known GLOBAL PROPERTY "FOUNDATION_TEST_${key}_DIRECTORY" SET)
  if(known)
    message(FATAL_ERROR "Duplicate test prerequisite declaration: ${name}")
  endif()
  set_property(GLOBAL APPEND PROPERTY FOUNDATION_REGISTERED_TESTS "${name}")
  set_property(GLOBAL PROPERTY "FOUNDATION_TEST_${key}_DIRECTORY" "${CMAKE_CURRENT_SOURCE_DIR}")
  set_property(GLOBAL PROPERTY "FOUNDATION_TEST_${key}_TARGETS" "${ARGN}")
  get_property(capture_scheduled DIRECTORY PROPERTY FOUNDATION_DIRECTORY_TESTS SET)
  set_property(DIRECTORY APPEND PROPERTY FOUNDATION_DIRECTORY_TESTS "${name}")
  if(NOT capture_scheduled)
    cmake_language(DEFER CALL _foundation_capture_test_labels)
  endif()
endfunction()

# TEST DIRECTORY requires CMake 3.28. Read final labels in their own directory
# instead, after all local set_tests_properties calls. No deferred local variable
# arguments are needed; each directory retains its own explicit registration list.
function(_foundation_capture_test_labels)
  get_property(names DIRECTORY PROPERTY FOUNDATION_DIRECTORY_TESTS)
  foreach(name IN LISTS names)
    string(SHA256 key "${name}")
    get_property(labels TEST "${name}" PROPERTY LABELS)
    set_property(GLOBAL PROPERTY "FOUNDATION_TEST_${key}_LABELS" "${labels}")
  endforeach()
endfunction()

function(_foundation_collect_tests directory output)
  get_property(tests DIRECTORY "${directory}" PROPERTY TESTS)
  get_property(children DIRECTORY "${directory}" PROPERTY SUBDIRECTORIES)
  foreach(child IN LISTS children)
    _foundation_collect_tests("${child}" nested)
    list(APPEND tests ${nested})
  endforeach()
  set(${output} "${tests}" PARENT_SCOPE)
endfunction()

function(foundation_finalize_test_prerequisites)
  _foundation_collect_tests("${CMAKE_SOURCE_DIR}" declared)
  get_property(registered GLOBAL PROPERTY FOUNDATION_REGISTERED_TESTS)
  list(SORT declared)
  list(SORT registered)
  if(NOT "${declared}" STREQUAL "${registered}")
    message(FATAL_ERROR "Every CTest case needs exactly one foundation_test_prerequisites declaration. Declared: ${declared}; registered: ${registered}")
  endif()
  set(inventory "{}")
  set(all_targets "")
  foreach(name IN LISTS registered)
    string(SHA256 key "${name}")
    get_property(targets GLOBAL PROPERTY "FOUNDATION_TEST_${key}_TARGETS")
    list(REMOVE_DUPLICATES targets)
    list(SORT targets)
    set(values "[]")
    set(index 0)
    foreach(target IN LISTS targets)
      if(NOT TARGET "${target}" OR NOT target MATCHES "^[A-Za-z0-9_][A-Za-z0-9_.+-]*$")
        message(FATAL_ERROR "Unknown or unsafe test prerequisite: ${name} -> ${target}")
      endif()
      string(JSON values SET "${values}" ${index} "\"${target}\"")
      math(EXPR index "${index}+1")
    endforeach()
    string(JSON inventory SET "${inventory}" "${name}" "${values}")
    get_property(labels GLOBAL PROPERTY "FOUNDATION_TEST_${key}_LABELS")
    foreach(label core tools integration fast gui)
      if(label IN_LIST labels)
        list(APPEND group_${label} ${targets})
      endif()
    endforeach()
    list(APPEND all_targets ${targets})
  endforeach()
  add_custom_target(foundation-tests DEPENDS ${all_targets})
  foreach(label core tools integration fast gui)
    add_custom_target(foundation-tests-${label} DEPENDS ${group_${label}})
  endforeach()
  if(TARGET foundation-gui-tests)
    add_dependencies(foundation-gui-tests foundation-tests-gui)
  endif()
  set(FOUNDATION_HAS_TEST_PREREQUISITES ON CACHE INTERNAL "Complete generated test prerequisite inventory" FORCE)
  file(WRITE "${CMAKE_BINARY_DIR}/test-prerequisites.json"
    "{\"schema_version\":1,\"tests\":${inventory}}\n")
endfunction()
